---
language: python
services: docker

env:
  global:
    - ROLE_NAME: users
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME sakibmoon.$ROLE_NAME
  - cd sakibmoon.$ROLE_NAME

script:
  # Run tests.
  - molecule test
